version: '3.8'

services:
  frontend:
    container_name: front
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: ./frontend
        target: /app
    env_file:
      -  ./config/.env_frontend

  backend:
    container_name: back
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
      - "3002:3002"
    volumes:
      - type: bind
        source: ./backend
        target: /app
    networks:
      - trans
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: postgres
# ログレベルFATAL以下のメッセージを出力しない設定。
    command: postgres -c log_min_messages=FATAL
# Debug用にログレベルをINFOに設定。
#    command: postgres -c log_min_messages=INFO -c log_destination=stderr -c log_statement=all -c log_connections=on
    ports:
      - "5432:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data
    networks:
      - trans
    env_file:
      -  ./backend/.env

  swagger:
    image: swaggerapi/swagger-ui:latest
    ports:
      - 8080:8080
    volumes:
      - ./swagger/api.yml:/api.yml
    environment:
      SWAGGER_JSON: /api.yml
    profiles:
      - debug

  swagger-editor:
    image: swaggerapi/swagger-editor:latest
    ports:
      - 8081:8080
    profiles:
      - debug

networks:
  trans:
    driver: bridge
