version: '3.8'

services:
  frontend:
    container_name: front
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: ./frontend
        target: /app
    env_file:
      -  ./config/.env_frontend

  backend:
    container_name: back
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
      - "3002:3002"
    volumes:
      - type: bind
        source: ./backend
        target: /app
    networks:
      - trans
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data
    networks:
      - trans
    env_file:
      -  ./backend/.env

  swagger:
    image: swaggerapi/swagger-ui:latest
    ports:
      - 8001:8080
    volumes:
      - ./api.yml:/api.yml
    environment:
      SWAGGER_JSON: /api.yml

  swagger-editor:
    image: swaggerapi/swagger-editor:latest
    ports:
    - 8002:8080

networks:
  trans:
    driver: bridge
