version: '3.8'

services:
  frontend:
    container_name: front
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: ./frontend
        target: /app

  backend:
    container_name: back
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
    - type: bind
      source: ./backend
      target: /app
    networks:
      - trans

  db:
    image: postgres:14
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
    - type: bind
      source: ${DB_STORAGE_DIR}
      target: /var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - trans

networks:
  trans:
    driver: bridge