openapi: 3.0.0
info:
  version: 1.0.0
  title: ft_transcendence API
  description: API Document for ft_transcendence
servers:
  - url: "http://localhost:3001"

tags:
  - name: health
    description: ヘルスチェック
  - name: chatRoom
    description: チャットルーム
paths:
  /health:
    get:
      tags: 
        - health
      summary: Health check
      description: ヘルスチェック
      responses:
        200:
          description: 成功例
          content:
            application/json:
              schema:
                type: object
                properties:
                  health:
                    type: string
                    example: OK
  /chatroom:
    get:
      tags:
        - chatRoom
      summary: get chatRoom List
      description: chatRoom情報の一覧を取得
      responses:
        200:
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/chat_room_res'

components:
  schemas:
    chat_room_res:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: Tom Brady