openapi: 3.0.0
info:
  version: 1.0.0
  title: ft_transcendence API
  description: API Document for ft_transcendence
servers:
  - url: "http://localhost:3001"

tags:
  - name: health
    description: ヘルスチェック
  - name: user
    description: ユーザー

paths:
  /health:
    get:
      tags: 
        - health
      summary: Health check
      description: ヘルスチェック
      responses:
        200:
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/health'

  /user:
    post:
      tags:
        - user
      summary: user
      description: ユーザーの作成
      requestBody:
        description: create a new user
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/user_create_req'
      responses:
        200:
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user_create_res'

  /user/{userID}:
    get:
      tags:
        - user
      summary: get user by ID
      description: IDを指定してuser情報を取得
      parameters:
        - name: userID
          required: true
          description: id
          in: path
          schema:
            type: integer
      responses:
        200:
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user_get_res'

  /user/friends/{userID}:
    get:
      tags:
        - user
      summary: get friends
      description: パラメータ(userID)のフレンドを取得
      parameters:
        - name: userID
          required: true
          in: path
          schema:
            type: integer
      responses:
        200:
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/friends_get_res'

  /user/friends:
    post:
      tags:
        - user
      summary: request or accept friendship
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/friends_post_req'
      responses:
        200:
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/friends_post_req'

  /user/friends/pending/{userID}:
    get:
      tags:
        - user
      summary: get pending list
      description: パラメータ(userID)のフレンド待機リストを取得
      parameters:
        - name: userID
          required: true
          in: path
          schema:
            type: integer
      responses:
        200:
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/friends_get_res'

components:
  schemas:
    health:
      type: object
      properties:
        health:
          type: string
          example: OK

    user_create_req:
      type: object
      properties:
        name:
          type: string
          example: Tom Brady
        password:
          type: string
          example: password

    user_create_res:
      type: object
      properties:
        id:
          type: integer
          example: 1

    user_get_res:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: Tom Brady
  
    friends_get_res:
      type: array
      items:
        type: object
        properties:
          id:
            type: integer
            example: 1
          name:
            type: string
            example: Nick Foles
    
    friends_post_req:
      type: object
      properties:
        from:
          type: integer
          example: 1
        to:
          type: integer
          example: 2
