name: lint Dockerfile
run-name: lint Dockerfile by ${{ github.actor }}
on: [push]
jobs:
  Lint-and-Format:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Lint Dockerfile
        run: make lint-dockerfile
