name: spell check
run-name: spell check by ${{ github.actor }}
on: [push]
jobs:
  Spell-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: spell check
        run: make spell-check
